version: '3'
services:
  school:
    image: varaprasad220/school
    ports:
      - "81:80"
    deploy:
      replicas: 3
  library:
    image: varaprasad220/library
    ports:
      - "82:80"
    deploy:
      replicas: 6
  aws:
    image: varaprasad220/hospital
    ports:
      - "83:80"
    deploy:
      replicas: 3
  movies:
    image: varaprasad220/moviesservice
    ports:
      - "84:80"
    deploy:
      replicas: 4
